Repository FSU-SP2023-SELab/group-1-lottopool, pull requests merged in 2023-02, with the labels that each got.

#21 Configure Frontend and Call Backend API
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  backend/requirements.txt
  backend/src/__init__.py
  frontend/.prettierrc
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.module.css
  frontend/src/App.tsx
  frontend/src/components/hello-world-example/hello-world-example.tsx
  frontend/src/components/hello-world-example/index.ts
  frontend/src/components/hello-world-example/types.d.ts
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/routes/home-page.tsx
  frontend/tailwind.config.js
Labels: frontend

#22 Add Style Guide for Backend (and a bit of Frontend) (And Actions)
  .github/workflows/testing.yml
  .vscode/extensions.json
  .vscode/settings.json
  backend/setup.cfg
  backend/setup.py
  backend/src/__init__.py
  backend/src/blueprints/__init__.py
  backend/src/blueprints/api.py
  backend/src/blueprints/index.py
  backend/src/middleware/__init__.py
  backend/src/middleware/prefix.py
  backend/tests/conftest.py
  backend/tests/test_example.py
  backend/wsgi.py
Labels: enhancement

#23 Fix env arg not being available at frontend build time
  docker-compose.yml
  frontend/Dockerfile
Labels: bug, devops

#24 Add Build Pipeline
  .github/workflows/building.yml
Labels: devops
